language: cpp
compiler: gcc
sudo: require
dist: trusty

addons:
  apt:
    sources:
      - sourceline: "ppa:beineri/opt-qt593-trusty"
    packages:
      - qt59base

install:
  - source /opt/qt*/bin/qt*-env.sh

before_script:
  - sudo bash -ex resources/bootstrap-container.sh

script:
  - git submodule update --init --recursive
  - bash -ex resources/build-appimages.sh

after_success:
  - ls -lh
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  # make sure only pushes to rewrite create a new release, otherwise pretend PR and upload to transfer.sh
  - if [ "$TRAVIS_BRANCH" != "rewrite" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - bash ./upload.sh appimageupdate*.AppImage* AppImageUpdate*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
